
@startuml textio_structure
!include _skin_settings.iuml

' ******************************************************************************

interface TextIOInterface
{
    + {abstract} **void** open()
    + {abstract} **void** load()
    + {abstract} **void** close()
}

class TextIO implements TextIOInterface
{
    - **TextstreamInterface?** _ts
___
    + **void** open()
    + **void** load()
    + **bool** close()
}
TextIO *-- TextstreamInterface

' ******************************************************************************

enum TextstreamType
{
    * MEMORY
    * DISK
}

interface TextstreamInterface
{
    + {abstract} **void** close()
    + {abstract} **void** update()
    + {abstract} **bool** is_eof()
}
TextstreamInterface -up-> TextstreamType

abstract class TextstreamBase implements TextstreamInterface
{
    + **bool** is_eof()
}

class TextstreamDisk extends TextstreamBase
{
    + **void** close()
    + **void** update()
}

class TextstreamMemory extends TextstreamBase
{
    + **void** close()
    + **void** update()
}

' ******************************************************************************

interface LexerInterface extends TextIOInterface

note right of LexerInterface
    Return type of
     ""make_lexer()""
endnote

abstract class LexerBase implements LexerInterface
abstract class LexerBase extends    TextIO

class Lexer <<implementation>> extends LexerBase

note right of Lexer
    Returned object of
        ""make_lexer()""
endnote

' ******************************************************************************

@enduml
